In [1]:
from pathlib import Path
import json
import pickle
import numpy as np
import pandas as pd
from bertopic import BERTopic

/home/leobaro/workspace/personal/nina-repo/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
base_dir = Path("./")

In [3]:
def load_results(output_dir):
    with open(output_dir / "params.json", 'r') as f:
        params = json.load(f)

    topic_model = BERTopic.load(output_dir / "saved_model", embedding_model=params["embedding_model_name"])

    with open(output_dir / "docs.pkl", 'rb') as f:
        docs = pickle.load(f)

    embeddings = np.load(output_dir / f"embeddings_{params['embedding_model_name']}.npy")

    chunks_with_topic = pd.read_csv(output_dir/"chunks_with_topic.csv")

    return topic_model, embeddings, docs, chunks_with_topic

# La_Voyeuse_interdite

In [9]:
data_root = Path(base_dir) / "topic_modeling_data"
experiment_name = "nina_Bouraoui_La_Voyeuse_interdite"
output_dir = Path(base_dir) / f"topic_modeling_output/{experiment_name}"

In [10]:
topic_model, embeddings, docs, chunks_with_topic = load_results(output_dir)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 9420.40it/s]

In [11]:
topic_model.get_topic_info()

,Topic,Count,Name,Representation,KeyBERT,Representative_Docs
0,-1,263,-1_corps_rue_chambre_main,"[corps, rue, chambre, main, hommes, femmes, ou...","[autour, entends, regarder, maison, porte, vie...",NaN
1,0,150,0_soleil_solitude_larmes_tête,"[soleil, solitude, larmes, tête, tristesse, vi...","[tristesse, larmes, sombre, esprit, pleurs, om...",NaN
2,1,59,1_père_mère_sexe_regard,"[père, mère, sexe, regard, maman, porte, chamb...","[mère, père, maman, enfant, coupable, tristess...",NaN
3,2,58,2_noir_peau_chair_yeux,"[noir, peau, chair, yeux, bout, terre, sang, r...","[ventre béant, doigts dévastateurs, visage, mo...",NaN
4,3,38,3_veines_sang_lait_rouge,"[veines, sang, lait, rouge, chair, intérieur, ...","[pleine sang, pleines veines, douleur, blessur...",NaN
5,4,28,4_tante_canapé_mère_table,"[tante, canapé, mère, table, menthe, lance, ta...","[tante, grand mère, sœur, mère, cousine, puiss...",NaN
6,5,24,5_chant_nuit_âmes_pierre,"[chant, nuit, âmes, pierre, enfants, temps, fi...","[esprits, âmes, jalouses, dernière nuit, peure...",NaN
7,6,23,6_fenêtre_chambre_objets_couleur,"[fenêtre, chambre, objets, couleur, lit, tabou...","[chambres, chambre, désordonnée, petite lampe,...",NaN
8,7,22,7_attendre_porte_fière_événement,"[attendre, porte, fière, événement, fête, ride...","[entrouverte, porte entrée, porte, bourreau, e...",NaN
9,8,22,8_voitures_rue_hommes_abandonné,"[voitures, rue, hommes, abandonné, instants, l...","[hommes rue, trottoirs, disparaître, cesse, ru...",NaN
10,9,20,9_choses_imagination_monde_monotonie,"[choses, imagination, monde, monotonie, réel, ...","[imaginaire, imagination, illusion, désordonné...",NaN
11,10,20,10_sable_arbre_roses_bois,"[sable, arbre, roses, bois, douce, savais, des...","[arbre jardinet, pierres roses, jardin, terras...",NaN
12,11,19,11_jeunesse_mâles_beaux_nature,"[jeunesse, mâles, beaux, nature, loi, femmes, ...","[féminin, femmes, féminine, fautive, femelles,...",NaN
13,12,19,12_nuit_rêve_sommeil_mort,"[nuit, rêve, sommeil, mort, demain, devais, de...","[rêves, rêve, dernière nuit, cauchemars, tragi...",NaN
14,13,15,13_gauche_robe_femmes_paquet,"[gauche, robe, femmes, paquet, tas, ventre, ti...","[seins forme, mère corps, forme quilles, corps...",NaN
15,14,14,14_filles_fenêtres_fillettes_jeunes filles,"[filles, fenêtres, fillettes, jeunes filles, j...","[filles cloîtrées, filles maisons, petites fil...",NaN
16,15,14,15_mères_mère_bracelets_petit,"[mères, mère, bracelets, petit, petite, honneu...","[grand mères, belle mère, mère corps, mère, mè...",NaN
17,16,11,16_eau_noirs_air_autour,"[eau, noirs, air, autour, attraper, ange, conn...","[eau sacrée, eau, enfoncer, mouillait, pot hen...",NaN
18,17,11,17_beauté_soleil_néant_terre,"[beauté, soleil, néant, terre, vide, centre, s...","[ombre, solennel, disparaît, silence solennel,...",NaN
19,18,11,18_oui_attardant_asphalte_atteint,"[oui, attardant, asphalte, atteint, coins reco...","[mère, fille, fillette, femme, chambre enfant,...",NaN
20,19,11,19_sexe_projection_prêt_adolescente,"[sexe, projection, prêt, adolescente, calme, c...","[sexe béant, sexe, sexes, sexe adolescente, vi...",NaN
21,20,10,20_mort_pierre_chair_poing,"[mort, pierre, chair, poing, apparente, ferme,...","[mort, meurt, morte, quitta, fermer, ferme, ou...",NaN
22,21,10,21_cigales_criquets_fougères_orchestre,"[cigales, criquets, fougères, orchestre, or, a...","[symphonie, orchestre, chant, fougères, hymne,...",NaN
23,22,10,22_hier_simple_fuit_demain,"[hier, simple, fuit, demain, temps, désir, cou...","[demain, temps, moment, pourtant, attendre, he...",NaN
24,23,9,23_cheveux_bouge_robe_inutile,"[cheveux, bouge, robe, inutile, blanc, belle, ...","[visage, visages, ridicule, robe longue, yeux ...",NaN
25,24,9,24_chauffeur_voiture_véhicule_portes,"[chauffeur, voiture, véhicule, portes, dernièr...","[chauffeur, véhicule, voiture, apercevoir, por...",NaN
26,25,9,25_payer_sais_corps_bouger,"[payer, sais, corps, bouger, ballottant, cland...","[fallait, disgrâce, péché, voulais, échappé, p...",NaN
27,26,8,26_cuisine_table_odeur_chiffon,"[cuisine, table, odeur, chiffon, caissette, bu...","[petite cuisine, vieille odeur, poussière, cui...",NaN
28,27,8,27_petite fille_fille_petite_sourire,"[petite fille, fille, petite, sourire, appelai...","[petite fille, fille, plaindre, tromperie, pet...",NaN
29,28,8,28_beauté_fleurs_audaces_attrait irrésistible,"[beauté, fleurs, audaces, attrait irrésistible...","[beauté, beaux, belle, fleur, attrait irrésist...",NaN
30,29,7,29_côtes_genoux_coups_sol,"[côtes, genoux, coups, sol, doigts, acharner, ...","[clouée sol, désespérément, laissait, clouée, ...",NaN

In [14]:
topic_model.visualize_documents(docs, topics=[1, 0, 11, 14, 15, 27])

# Garçon Manqué

In [4]:
data_root = Path(base_dir) / "topic_modeling_data"
experiment_name = "nina_Bouraoui_Gar_on_manqu"
output_dir = Path(base_dir) / f"topic_modeling_output/{experiment_name}"

In [5]:
topic_model, embeddings, docs, chunks_with_topic = load_results(output_dir)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 7917.31it/s]

In [7]:
topic_model.get_topic_info()

,Topic,Count,Name,Representation,KeyBERT,Representative_Docs
0,-1,429,-1_sais_amour_visage_voix,"[sais, amour, visage, voix, sœur, vie, secret,...","[grand mère, mère, famille, sœur, parents, pèr...",NaN
1,0,158,0_algérienne_algérien_algériens_arabe,"[algérienne, algérien, algériens, arabe, franç...","[algériennes, algériens, algérienne, algérien,...",NaN
2,1,150,1_mer_plage_vagues_sable,"[mer, plage, vagues, sable, pont, marée, loin,...","[mer vient, chercher mer, loin mer, marée, air...",NaN
3,2,57,2_père_voyages_homme_travail,"[père, voyages, homme, travail, frère, savait,...","[grand père, père voix, père homme, mère père,...",NaN
4,3,54,3_femmes_yeux_visage_peau,"[femmes, yeux, visage, peau, mains, corps, bar...","[peau douce, peau blanche, mère peau, visage, ...",NaN
...,...,...,...,...,...,...
62,61,8,61_salon bleu_salon_petit salon_attend,"[salon bleu, salon, petit salon, attend, bleu,...","[porte, entrée, viendra, maison, quelqu, conna...",NaN
63,62,8,62_dangereux_adversaire_attentat_dangereuses,"[dangereux, adversaire, attentat, dangereuses,...","[dangereux, dangereuses, menace, peur, fragili...",NaN
64,63,8,63_feu_brûle_rouge_peau brûlante,"[feu, brûle, rouge, peau brûlante, silence cor...","[brûle, brûlante, brûlantes, peau brûlante, fe...",NaN
65,64,8,64_facile_reconnaître_oui_aimer,"[facile, reconnaître, oui, aimer, voyage, cher...","[facile, douceur, rentrer, heureux, voir, pour...",NaN
66,65,7,65_dors_peur_hante_mère raison,"[dors, peur, hante, mère raison, peur nuit, pe...","[peur silence, peur nuit, peur, rêve, visions,...",NaN

In [8]:
topic_model.visualize_documents(docs, topics=[0, 5, 2, 8])

# Mes Mauvaise pensees

In [17]:
data_root = Path(base_dir) / "topic_modeling_data"
experiment_name = "nina_Bouraoui_Mes_mauvaises_pens_es"
output_dir = Path(base_dir) / f"topic_modeling_output/{experiment_name}"

In [19]:
topic_model, embeddings, docs, chunks_with_topic = load_results(output_dir)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 8709.32it/s]

In [20]:
topic_model.get_topic_info()

,Topic,Count,Name,Representation,KeyBERT,Representative_Docs
0,-1,541,-1_mère_vie_jour_grand,"[mère, vie, jour, grand, sœur, crois, sais, fa...","[grands parents, grand mère, mère, parents, gr...",NaN
1,0,77,0_chanteuse_bruit_voix_chanson,"[chanteuse, bruit, voix, chanson, entends, cha...","[entends voix, voix mère, voix, voix appellent...",NaN
2,1,74,1_odeur_mer_cause_chaud,"[odeur, mer, cause, chaud, terre, fleurs, lumi...","[marchons, arrivée, peur chaude, sensuel, para...",NaN
3,2,63,2_peur_pensées_mauvaises pensées_mauvaises,"[peur, pensées, mauvaises pensées, mauvaises, ...","[peur savez, rêve peur, savez peur, peur peur,...",NaN
4,3,58,3_amour_amoureuse_amie_jamais,"[amour, amoureuse, amie, jamais, aime, amour a...","[manque amour, vois amour, amour vient, langag...",NaN
5,4,51,4_lettre numéro_lettre_numéro_champagne,"[lettre numéro, lettre, numéro, champagne, pho...","[lettre, vient maison, lettre numéro, sais aim...",NaN
6,5,48,5_algérien_algérienne_français_père,"[algérien, algérienne, français, père, grand p...","[algérienne, algérien, françaises, vacances fr...",NaN
7,6,44,6_piscine_eau_loin_nage,"[piscine, eau, loin, nage, corps, rocher, corp...","[piscine, corps eau, nage loin, eau, manque no...",NaN
8,7,44,7_père_fier_famille sais_fête,"[père, fier, famille sais, fête, père père, fa...","[père père, père vrai, regard père, sais père,...",NaN
9,8,41,8_violence_colère_sais faire_fille,"[violence, colère, sais faire, fille, monde, s...","[colère corps, colère revient, colère, violenc...",NaN
10,9,37,9_sens_coupable_jamais_libre,"[sens, coupable, jamais, libre, sentiment, cor...","[sens coupable, tristesse solitude, moimême, s...",NaN
11,10,35,10_larmes_pleure_cœur_pleurer,"[larmes, pleure, cœur, pleurer, envie, enfant,...","[envie pleurer, pleurer sais, pleuré, pleure v...",NaN
12,11,30,11_écriture_écris_roman_écrire,"[écriture, écris, roman, écrire, écriture écri...","[savez écriture, écriture écriture, écriture, ...",NaN
13,12,30,12_livre_livres_éditeur_vérité,"[livre, livres, éditeur, vérité, rêve, auteur,...","[vraiment écrivain, livre livre, écrivain, aut...",NaN
14,13,29,13_père_veux silence_silence_veux,"[père, veux silence, silence, veux, mort père,...","[père peur, père crois, peur père, mort père, ...",NaN
15,14,27,14_petite femme_mère_femme_petite,"[petite femme, mère, femme, petite, voir, sœur...","[mère mère, vient mère, mère grand, mère jamai...",NaN
16,15,24,15_adresse_silence_limites_happée,"[adresse, silence, limites, happée, dites, tél...","[silence veux, veux entendre, sais porte, sile...",NaN
17,16,23,16_honte_fur mesure_retrouve_brûlé,"[honte, fur mesure, retrouve, brûlé, tantôt, s...","[amoureux, sais fille, amour, crois aime, croi...",NaN
18,17,20,17_enfance_fille_enfants_homme,"[enfance, fille, enfants, homme, mots, père, e...","[mère enfant, enfance, petit fille, petite fil...",NaN
19,18,20,18_mourir_mort_cimetière_croire,"[mourir, mort, cimetière, croire, vivant, mort...","[enterré, failli mourir, mourir, cimetière, mo...",NaN
20,19,18,19_habits_yeux_cheveux_longs,"[habits, yeux, cheveux, longs, super, beauté, ...","[beauté, cause beauté, ressembler, yeux sais, ...",NaN
21,20,18,20_vois_notion_glisse_espace,"[vois, notion, glisse, espace, rester, tête, j...","[sentiment vie, mots tête, chose ridicule, ise...",NaN
22,21,18,21_sais peur_jeune homme_regarde sais_peur,"[sais peur, jeune homme, regarde sais, peur, i...","[jeune homme, sais garçon, garçon, peur voir, ...",NaN
23,22,17,22_corps_mère_bras_cause,"[corps, mère, bras, cause, corps mère, soudain...","[abandon mère, mère part, corps mère, sang mèr...",NaN
24,23,16,23_monte voiture_soin_froid_voiture,"[monte voiture, soin, froid, voiture, honte, a...","[dis mère, femme, folle, pourriez, donne, gêné...",NaN
25,24,15,24_chiens_frappe_chien_sauve,"[chiens, frappe, chien, sauve, petit chien, gr...","[chiens, chien, petit chien, animaux, chien en...",NaN
26,25,15,25_peur_mère peur_mère_phobies,"[peur, mère peur, mère, phobies, peur peur, pè...","[peur mère, mère peur, peur père, peur peur, m...",NaN
27,26,14,26_jouait_tombe_jeunes_héroïne,"[jouait, tombe, jeunes, héroïne, aimait, honte...","[fille héroïne, fille, chanteuse tient, yeux f...",NaN
28,27,14,27_jure_attend_prends_aimerais faire,"[jure, attend, prends, aimerais faire, avis, i...","[puisqu, folle, aimerais, veux, crois, aimerai...",NaN
29,28,14,28_enfance_enfants_soigne_enfant,"[enfance, enfants, soigne, enfant, saigne, oui...","[enfance, enfants, enfant, mots mère, parents,...",NaN
30,29,13,29_lire_compte_anglaises_reconnais,"[lire, compte, anglaises, reconnais, vide, pro...","[amie sœur, mère lit, donne sœur, lectrice, mè...",NaN
31,30,12,30_père_images_image_jeun,"[père, images, image, jeun, esse, père porte, ...","[père visage, yeux père, image père, savez pèr...",NaN
32,31,12,31_mort père_mort_morte_reprises,"[mort père, mort, morte, reprises, surprise, p...","[mort famille, failli mourir, amie mort, mouri...",NaN
33,32,12,32_grand_grand mère_mère_rire,"[grand, grand mère, mère, rire, glace, petit o...","[grand mère, mère cache, mère, amour mère, mèr...",NaN
34,33,11,33_jolie_ouvre_trouve_reconnais,"[jolie, ouvre, trouve, reconnais, filles, arri...","[jolie, aime filles, voyait, aime, douce, jalo...",NaN
35,34,11,34_jardin_neige_champs_village,"[jardin, neige, champs, village, campagne, pie...","[rêve, jardin, jardin père, jardin maison, rac...",NaN
36,35,11,35_couple_dernière_fille père_considère,"[couple, dernière, fille père, considère, marc...","[couple, ensemble, adoré connaître, adoré, fil...",NaN
37,36,11,36_nuit_nuit peur_peur nuit_séisme,"[nuit, nuit peur, peur nuit, séisme, festival,...","[peur nuit, nuit peur, entends sonnerie, nuit,...",NaN
38,37,10,37_vide_nourrit_verre_fantôme,"[vide, nourrit, verre, fantôme, creuse, limite...","[disparaît, vide creuse, cesse, intérieur, exi...",NaN
39,38,10,38_nudité_nue_baisser_peau,"[nudité, nue, baisser, peau, immense, salon, r...","[nudité, dégoût, visage, femme, fille, ferme y...",NaN
40,39,9,39_écrire_totale_voulu écrire_absence,"[écrire, totale, voulu écrire, absence, pleuré...","[voulu écrire, écriture, écrire, écrivais, sai...",NaN
41,40,9,40_devoir_étrangère_vis_supporter,"[devoir, étrangère, vis, supporter, folle sais...","[veux quitter, veux, vis vis, venir, vis, mada...",NaN
42,41,9,41_arrive_rêve_mots_autour,"[arrive, rêve, mots, autour, cheveux parfum, c...","[rêve, voyais, amoureuse, nuit regarde, jamais...",NaN
43,42,9,42_maman_nuit_rentre_temps,"[maman, nuit, rentre, temps, appelle, insiste,...","[heure père, mère veut, mère comprends, séduir...",NaN
44,43,9,43_ciel_nuages_image_nature,"[ciel, nuages, image, nature, infini, perd, ga...","[loin ciel, ciel, grand mère, sais mère, voir ...",NaN
45,44,9,44_écriture_papier_livre_temps,"[écriture, papier, livre, temps, noir, faut ar...","[livre écriture, écriture jour, écriture écrit...",NaN
46,45,9,45_chat_années_petit_histoire,"[chat, années, petit, histoire, vivre, peur oc...","[sais vieillir, années années, crois vie, viei...",NaN
47,46,8,46_souvenir_refaire_dois_viens,"[souvenir, refaire, dois, viens, vérité, garde...","[signifie, laisse, devient, existe, viens voir...",NaN
48,47,8,47_chair_gestes_petite fille_table,"[chair, gestes, petite fille, table, sec, ache...","[pensé, déjeuner, acheté, mains, donne sœur, p...",NaN
49,48,8,48_souffre_tristesse_sais_monter,"[souffre, tristesse, sais, monter, mal, accid,...","[mère souffre, mère prend, crois mère, sais tr...",NaN
50,49,7,49_portée_réveille_chambre_mère,"[portée, réveille, chambre, mère, aime place, ...","[mère endormie, oublie mère, mère appartement,...",NaN

In [22]:
topic_model.visualize_documents(docs, topics=[11, 5, 13, 14, 22, 7, 3, 8, 28 ])